Fix Callable WP Command doesn't exist and Plugin Activation Error
Fixes the following errors as of 2/25/2022;
Error: Callable "S3_Uploads\\WP_CLI_Command" does not exist, and cannot be registered as `wp s3-uploads`.
Error: 's3-uploads' is not a registered wp command. See 'wp help' for available commands.